version: '3.8'
services:
  dev-db:
    image: postgres
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: munaseq
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: munaseq_db
    networks:
      - munaseq-network
  test-db:
    image: postgres
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: munaseq_test
    networks:
      - munaseq-network

networks:
  munaseq-network:
